version: '3.9'

services:
  activemq:
    build: ./ActiveMQ
    networks:
      - walletconnect-rs-relay
    ports:
      - 5672:5672
      - 8086:8161
    volumes:
      - rs-relay-test-data-storage:/activemq
    environment:
      - ACTIVEMQ_USERNAME=admin
      - ACTIVEMQ_PASSWORD=admin
      - ACTIVEMQ_WEBADMIN_USERNAME=admin
      - ACTIVEMQ_WEBADMIN_PASSWORD=admin

  mongo:
    image: mongo:4
    networks:
      - walletconnect-rs-relay
    ports:
      - 27017:27017
    volumes:
      - rs-relay-test-data-storage:/mongo
    healthcheck:
      test:
        [
          "CMD",
          "mongo",
          "--eval",
          "'db.runCommand(\"ping\").ok'",
          "localhost:27017/test",
          "--quiet"
        ]
      interval: 5s
      timeout: 5s
      retries: 5
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
      - MONGO_INITDB_DATABASE=relay

  mongo-express:
    image: mongo-express
    networks:
      - walletconnect-rs-relay
    ports:
      - 8085:8081
    depends_on:
      mongo:
        condition: service_healthy
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=admin
      - ME_CONFIG_MONGODB_URL="mongodb://admin:admin@mongo:27017"

  redis:
    image: redis:6-alpine
    networks:
      - walletconnect-rs-relay
    ports:
      - 6379:6379
    volumes:
      - rs-relay-test-data-storage:/redis
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 5s
      timeout: 5s
      retries: 5

  redisinsight:
    image: redislabs/redisinsight:latest
    networks:
      - walletconnect-rs-relay
    ports:
      - 8001:8001

  minio:
    image: minio/minio
    networks:
      - walletconnect-rs-relay
    ports:
      - "9000:9000"
      - "9090:9090"
    volumes:
      - rs-relay-test-data-storage:/minio
    environment:
      - "MINIO_ACCESS_KEY=AKIAIOSFODNN7EXAMPLE"
      - "MINIO_SECRET_KEY=wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY"
    command: server /data --console-address ":9090"

  createbuckets:
    image: minio/mc
    depends_on:
      - minio
    networks:
      - walletconnect-rs-relay
    entrypoint: >
      /bin/sh -c "
      /usr/bin/mc config host add myminio http://minio:9000 AKIAIOSFODNN7EXAMPLE wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY;
      /usr/bin/mc mb myminio/datalake;
      /usr/bin/mc anonymous set upload myminio/datalake;
      /usr/bin/mc anonymous set download myminio/datalake;
      /usr/bin/mc anonymous set public myminio/datalake;
      exit 0;
      "

  jaeger:
    image: jaegertracing/all-in-one:latest
    networks:
      - walletconnect-rs-relay
    ports:
      - 4317:4317
      - 16686:16686
    volumes:
      - rs-relay-test-data-storage:/jaeger
    environment:
      - COLLECTOR_OTLP_ENABLED=true
  # aws-otel-collector:
  #   image: amazon/aws-otel-collector:latest
  #   command: --config=/otel-config.yaml
  #   networks:
  #     - walletconnect-rs-relay
  #   ports:
  #     - 4318:4317
  #   volumes:
  #     - ./otel/config.yaml:/otel-config.yaml
  #   healthcheck:
  #     test: [ "CMD", "/healthcheck" ]
  #     interval: 5s
  #     timeout: 5s
  #     retries: 5
  #   environment:
  #     - AWS_ACCESS_KEY_ID
  #     - AWS_SECRET_ACCESS_KEY
  #     - AWS_REGION

networks:
  walletconnect-rs-relay:
    ipam:
      driver: default
      config:
        - subnet: 172.10.1.0/16

volumes:
  rs-relay-test-data-storage:
