name: ⚙️ Debug - Validate
on:
  push:
    branches:
      - 58-migrate-ti-dedicated-aws-account

permissions:
  contents: read
  checks: write
  id-token: write

jobs:
  ci:
    name: CI
    uses: WalletConnect/ci_workflows/.github/workflows/ci.yml@0.1.3
    secrets: inherit
    with:
      check-infra: true
      check-app: true

  validate-staging:
    name: Validate - Staging
    uses: ./.github/workflows/sub-validate.yml
    secrets: inherit
    with:
      stage: staging
      stage-url: https://staging.${{ vars.SUBDOMAIN_NAME }}.walletconnect.com

  validate-prod:
    name: Validate - Prod
    uses: ./.github/workflows/sub-validate.yml
    secrets: inherit
    with:
      stage: prod
      stage-url: https://${{ vars.SUBDOMAIN_NAME }}.walletconnect.com
