name: deploy
on:
  workflow_dispatch:
    inputs:
      name: environment
      type: choice
      options: 
       - dev
       - staging 
  workflow_call:

concurrency:
  # Only allow for one action to run at once, queue any others
  group: cd
  # Don't cancel existing
  cancel-in-progress: false

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: ${{ inputs.environment }}
      url: https://${{ inputs.environment }}.verify.walletconnect.com/health
    needs:
      - get-version
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - id: terraform
        uses: WalletConnect/actions/actions/deploy-terraform/@master
        env:
          TF_VAR_project_registry_auth_token: ${{ secrets.PROJECT_REGISTRY_AUTH_TOKEN }}
          TF_VAR_image_version: ${{ github.head_ref }}.${{ github.sha }}
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-central-1
          environment: ${{inputs.environment}}
          app-name: ${{ github.event.repository.name }}
