name: ❖ Validate

on:
  workflow_call:
    inputs:
      stage:
        description: 'the environment to validate'
        type: string
        default: 'staging'
      stage-url:
        description: 'the URL of the environment'
        type: string
        default: https://${{ vars.SUBDOMAIN_NAME }}.walletconnect.com
      rust-toolchain:
        description: 'The Rust version to use'
        type: string
        default: ${{ vars.RUST_VERSION }}

permissions:
  contents: read
  checks: write
  id-token: write

jobs:
  health-check:
    name: Health Check - ${{ inputs.stage }}
    runs-on:
      group: ${{ vars.RUN_GROUP }}
    environment:
      name: ${{ inputs.stage }}
      url: ${{ inputs.stage-url }}
    steps:
      - name: health-check
        run: curl "${{ inputs.stage-url }}"

  integration-tests-ts:
    name: TS Integration Tests - ${{ inputs.stage }}
    runs-on:
      group: ${{ vars.RUN_GROUP }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18.x
          cache: 'yarn'
          cache-dependency-path: '**/yarn.lock'

      - name: Yarn Install
        run: yarn install

      - name: Yarn Integration Tests
        run: yarn integration:${{ inputs.stage }}
